language: cpp
sudo: required

jobs:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
            - valgrind
            - gcovr
            - clang-3.9
          sources:
            - ubuntu-toolchain-r-test

install:
  #start code from https://riptutorial.com/cmake/example/4723/configure-travis-ci-with-newest-cmake
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.17.3-Linux-x86_64.tar.gz
  - echo "f3546812c11ce7f5d64dc132a566b749 *cmake-3.17.3-Linux-x86_64.tar.gz" > cmake_md5.txt
  - md5sum -c cmake_md5.txt
  - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.17.3-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}
  #end code of riptutorial.com
  - ./script/install_criterion.sh

script:
  - cmake .
  - cmake --build .
  - ./Tetra-Engine-Testing

notifications:
email: false