language: cpp
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
            - valgrind
            - gcovr
            - clang-3.9
          sources:
            - ubuntu-toolchain-r-test

install:
  - sudo ./script/install_cmake.sh
  - ./script/install_criterion.sh

script:
  - cmake .
  - cmake --build .
  - ./Tetra-Engine-Testing

notifications:
email: false