language: cpp
sudo: required

jobs:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
            - valgrind
            - gcovr
            - clang-3.9
          sources:
            - ubuntu-toolchain-r-test

install:
  #start code from https://riptutorial.com/cmake/example/4723/configure-travis-ci-with-newest-cmake
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3.tar.gz
  - tar -xvf cmake-3.17.3.tar.gz
  - mv cmake-3.17.3 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}
  #end code of riptutorial.com
  - ./script/install_criterion.sh

script:
  - cmake .
  - cmake --build .
  - ./Tetra-Engine-Testing

notifications:
email: false